player:
  autodetect: true
log_parsing:
  enabled: true
  cycle_on_start: false
guild_tracking:
  enabled: true
  output_to_discord: true
  interval: 25
  in_game_dump:
    enabled: true
    days_until_inactive: 30
  open_dkp:
    enabled: true
    client_id: 6192bc2cf4680
    root_endpoint: https://7gnjtigho4.execute-api.us-east-2.amazonaws.com/beta
    off_duty_metric:
      key: calculated_30
      threshold: .40
game:
  root_folder: C:\Program Files (x86)\Steam\steamapps\common\Everquest F2P
buffing:
  enabled: true
  restrict_to_guildies: true
  spells:
    Voice of Clarivoyance:
      spell_slot: 6
      cast_time: 12
    Hastening of Salik:
      spell_slot: 7
      cast_time: 9
